# Generated by roxytest: do not edit by hand!

# File R/DragenTso.R: @testexamples

test_that("Function DragenTso() @ L83", {
  
  cls <- DragenTso; tool <- "dragentso"
  indir <- system.file("extdata", tool, package = "tidydragen")
  odir <- tempdir()
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = "run1")
  (lf <- list.files(odir, pattern = "dragentso_.*parquet", full.names = FALSE))
  # smallvariants: CVO [Small Variants] section only; empty-gene row kept
  sv <- nemo::read_parquet_grep(odir, lf, "sampleA_dragentso_smallvariants")
  expect_equal(nrow(sv), 1287L)
  expect_equal(sv$gene[sv$pos == 2488153], "TNFRSF14")
  expect_true(is.na(sv$gene[sv$pos == 4367323]))
  expect_equal(sv$vaf[sv$pos == 2488153], 0.4768)
  expect_equal(sv$pos[1], 2488153L)
  # fusions: v2 18-column shape, lowercase tidy names
  fu <- nemo::read_parquet_grep(odir, lf, "sampleA_dragentso_fusions")
  expect_equal(fu$gene1[1], "EML4")
  expect_equal(fu$vaf[1], 0.00682348716107)
  # tmbtrace: 27 v2 columns
  tt <- nemo::read_parquet_grep(odir, lf, "sampleA_dragentso_tmbtrace")
  expect_equal(tt$gene[1], "TNFRSF14")
  expect_equal(tt$consequence[1], "missense_variant")
  # tmbmsaf: leading max_somatic_af + variant columns
  tm <- nemo::read_parquet_grep(odir, lf, "sampleA_dragentso_tmbmsaf")
  expect_equal(tm$gene[1], "TP53")
  # exoncov / genecov
  ec <- nemo::read_parquet_grep(odir, lf, "sampleA_dragentso_exoncov")
  expect_equal(ec$mean[1], 3004.16)
  gc <- nemo::read_parquet_grep(odir, lf, "sampleA_dragentso_genecov")
  expect_false("median" %in% names(gc))
  expect_equal(gc$gene[1], "TNFRSF14")
  # SAR fan-out: sarmain / sarqc / sarqcthr / sarsnv / sarcnv / sarswds / sarsw
  si <- nemo::read_parquet_grep(odir, lf, "sampleA_dragentso_sarmain")
  expect_equal(si$sample_id, "sampleA")
  expect_equal(nrow(si), 1L)
  qc <- nemo::read_parquet_grep(odir, lf, "sampleA_dragentso_sarqc\\.parquet")
  expect_equal(nrow(qc), 1L)
  expect_equal(qc$contamination_score, 50)
  expect_equal(qc$tmb_per_mb, 2.4)
  expect_equal(qc$msi_pct_unstable_sites, 0)
  expect_equal(qc$pct_target_04x_mean, 94.7)
  expect_equal(si$library_type, "DNA")
  expect_true(si$analysis_completed)
  expect_equal(si$schema_version, "7.0.0")
  # sarqcthr: 6 QC metric rows (median_exon_coverage in two groups) with limits
  th <- nemo::read_parquet_grep(odir, lf, "sampleA_dragentso_sarqcthr")
  expect_equal(nrow(th), 6L)
  gsm <- th[th$metric == "gene_scaled_mad", ]
  expect_equal(c(gsm$lsl, gsm$usl), c(0, 0.059))
  expect_true(is.na(th$usl[th$metric == "pct_exon_1000x"]))
  expect_true(is.na(th$uom[th$metric == "contamination_score"]))
  sn <- nemo::read_parquet_grep(odir, lf, "sampleA_dragentso_sarsnv")
  expect_equal(nrow(sn), 10L)
  expect_equal(sn$hgnc[sn$pos == 2488153], "TNFRSF14")
  expect_equal(sn$consequence[sn$pos == 2488153], "missense_variant")
  expect_true(all(c("biotype", "iscanonical", "proteinid", "introns", "isjunctionpreserving") %in% names(sn)))
  expect_equal(sn$variant_type[sn$pos == 2488153], "SNV")
  expect_equal(sn$hgvsg[sn$pos == 2488153], "NC_000001.10:g.2488153A>G")
  # this sample reports no CNVs -> sarcnv is an empty (0-row) table with the schema cols
  cn <- nemo::read_parquet_grep(odir, lf, "sampleA_dragentso_sarcnv")
  expect_equal(nrow(cn), 0L)
  expect_true(all(c("gene", "cn_type") %in% names(cn)))
  ds <- nemo::read_parquet_grep(odir, lf, "sampleA_dragentso_sarswds")
  expect_equal(nrow(ds), 7L)
  expect_true("RefSeq" %in% ds$name)
  sw <- nemo::read_parquet_grep(odir, lf, "sampleA_dragentso_sarsw\\.parquet")
  expect_equal(nrow(sw), 1L)
  expect_true(!is.na(sw$software_version))
})

