# Generated by roxytest: do not edit by hand!

# File R/DragenVar.R: @testexamples

test_that("Function DragenVar() @ L120", {
  
  cls <- DragenVar; tool <- "dragenvar"
  indir <- system.file("extdata", tool, package = "tidydragen")
  odir <- tempdir()
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = "run1")
  (lf <- list.files(odir, pattern = "dragenvar_.*parquet", full.names = FALSE))
  # sampleA: whole-genome vc; SUMMARY section dropped, only prefilter/postfilter
  vcA <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_vc", lf, value = TRUE)))
  expect_equal(nrow(vcA), 2L)
  expect_setequal(vcA$section, c("prefilter", "postfilter"))
  expect_equal(vcA$mnps[vcA$section == "prefilter"], 51104)
  # SUMMARY-only metrics are gone with the dropped section
  expect_false("child_sample" %in% names(vcA))
  expect_true(all(vcA$region == "genome"))
  post <- vcA[vcA$section == "postfilter", ]
  expect_equal(post$total, 5031538)
  expect_equal(post$total_pct, 100)
  expect_equal(post$chrx_snps, 130382)
  # sampleB: targeted vc — region stripped to same tidy col, region col = targetreg
  vcB <- arrow::read_parquet(file.path(odir, grep("sampleB_dragenvar_vc", lf, value = TRUE)))
  expect_true(all(vcB$region == "targetreg"))
  expect_true(is.numeric(vcB$qc_region_callability_region1_pct))
  # cttso targeted vc emits a single postfilter row
  expect_equal(vcB$chrx_snps[vcB$section == "postfilter"], 11)
  # sv: count-only total + pct-paired PASS breakdown
  sv <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_sv", lf, value = TRUE)))
  expect_equal(sv$total_pass, 169)
  expect_equal(sv$del, 50)
  expect_equal(sv$del_pct, 29.59)
  # cnv
  # sampleA (somatic WGS): tumor purity + amplification pass rate; no SEX GENOTYPER preamble
  cnv <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_cnv", lf, value = TRUE)))
  expect_equal(nrow(cnv), 1L)
  expect_equal(cnv$purity_tumor, 0.54)
  expect_equal(cnv$n_amp_pass_pct, 86.54)
  expect_false("sex_karyotype" %in% names(cnv))
  # sampleB (cttso): SEX GENOTYPER preamble captured (not dropped) as columns on the one cnv row
  cnvB <- arrow::read_parquet(file.path(odir, grep("sampleB_dragenvar_cnv", lf, value = TRUE)))
  expect_equal(nrow(cnvB), 1L)
  expect_equal(cnvB$sex_karyotype, "XY")
  expect_equal(cnvB$sex_genotyper_confidence, 0.475)
  expect_false("purity_tumor" %in% names(cnvB))
  # tmb (4-col, no pct)
  tmb <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_tmb", lf, value = TRUE)))
  expect_equal(tmb$tmb, 3.46)
  expect_equal(tmb$vars_tot_input, 12004)
  # ploidy: split into `ploidystats` (sample scalars) + `ploidyratio` (per-chrom, long)
  plo <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_ploidystats", lf, value = TRUE)))
  expect_equal(plo$ploidy_est, "XX")
  expect_equal(plo$cov_x_pctile, 45.99)
  expect_false("cov_x_div_auto" %in% names(plo))
  pcr <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_ploidyratio", lf, value = TRUE)))
  expect_equal(pcr$ratio[pcr$chrom == "X"], 0.99)
  expect_equal(pcr$ratio[pcr$chrom == "1"], 1.00)
  # sampleB: 'median coverage'/'median / Autosomal median' naming -> same tidy names
  ploB <- arrow::read_parquet(file.path(odir, grep("sampleB_dragenvar_ploidystats", lf, value = TRUE)))
  expect_equal(ploB$cov_x_median, 19.24)
  expect_equal(ploB$ploidy_est, "XX")
  expect_false("cov_skewness" %in% names(ploB))
  pcrB <- arrow::read_parquet(file.path(odir, grep("sampleB_dragenvar_ploidyratio", lf, value = TRUE)))
  expect_equal(pcrB$ratio[pcrB$chrom == "X"], 0.99)
  # nuctrans: long, one row per transition code (e.g. AC)
  nt <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_nuctrans", lf, value = TRUE)))
  expect_equal(nrow(nt), 12L)
  expect_equal(nt$value[nt$transition == "AC"], 63)
  expect_equal(nt$value[nt$transition == "TG"], 45)
  # hethom: per-chromosome, one row per section/rg/chrom; nan ratio preserved
  hh <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_hethom", lf, value = TRUE)))
  expect_true(is.numeric(hh$hom))
  pre1 <- hh[hh$section == "prefilter" & hh$chrom == "1", ]
  expect_equal(pre1$het, 233196)
  expect_equal(pre1$het_hom_ratio, 1.348)
  postY <- hh[hh$section == "postfilter" & hh$chrom == "Y", ]
  expect_true(is.nan(postY$het_hom_ratio))
  # hrd (csv, 1 row)
  hrd <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_hrd", lf, value = TRUE)))
  expect_equal(hrd$hrd_score, 5L)
  expect_equal(hrd$loh_score, 2L)
  # microsat (JSON, 1 row): Settings dropped, numeric keys cast, result stays char
  msi <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_microsat", lf, value = TRUE)))
  expect_equal(nrow(msi), 1L)
  expect_equal(msi$sites_assessed, 14783)
  expect_equal(msi$sites_unstable, 204)
  expect_equal(msi$pct_unstable, 1.38)
  expect_equal(msi$result_valid, "true")
  # sum_jsd key absent in this DRAGEN version's JSON -> NA
  expect_true(is.na(msi$sum_jsd))
  expect_false(any(c("command", "outputprefix") %in% tolower(names(msi))))
  # ploidyvcf (native gz VCF parse): one row per contig, FORMAT DC:NDC split out
  pv <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_ploidyvcf", lf, value = TRUE)))
  xrow <- pv[pv$chrom == "chrX", ]
  expect_equal(xrow$dc, 45.991)
  expect_equal(xrow$ndc, 0.990984)
  expect_true(all(pv$filter == "PASS"))
  # gvcf (cttso): vc-shaped postfilter metrics; region -> targetreg column, pct auto-paired
  gv <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_gvcf", lf, value = TRUE)))
  expect_equal(nrow(gv), 1L)
  expect_equal(gv$region, "targetreg")
  expect_equal(gv$total, 1234)
  expect_equal(gv$snps, 1168)
  expect_equal(gv$snps_pct, 94.65)
  expect_equal(gv$titv_ratio, 2.99)
  expect_equal(gv$chrx_snps, 11)
  # contamination (cttso, flat JSON): SNPsUsed dropped, NaN p-value -> NA
  ct <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_contamination", lf, value = TRUE)))
  expect_equal(nrow(ct), 1L)
  expect_equal(ct$score, 50)
  expect_equal(round(ct$level, 4), 0.0402)
  expect_true(is.na(ct$pvalue))
  expect_false("snpsused" %in% tolower(names(ct)))
})

