# Generated by roxytest: do not edit by hand!

# File R/DragenVar.R: @testexamples

test_that("Function DragenVar() @ L86", {
  
  cls <- DragenVar; tool <- "dragenvar"
  indir <- system.file("extdata", tool, package = "tidydragen")
  odir <- tempdir()
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = "run1")
  (lf <- list.files(odir, pattern = "dragenvar_.*parquet", full.names = FALSE))
  # sampleA: whole-genome vc; SUMMARY section dropped, only prefilter/postfilter
  vcA <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_vc", lf, value = TRUE)))
  expect_equal(nrow(vcA), 2L)
  expect_setequal(vcA$section, c("prefilter", "postfilter"))
  expect_true(all(c("section", "rg", "region", "total", "total_pct", "chrx_snps") %in% names(vcA)))
  expect_equal(vcA$mnps[vcA$section == "prefilter"], 318)
  # SUMMARY-only metrics are gone with the dropped section
  expect_false("child_sample" %in% names(vcA))
  expect_true(all(vcA$region == "genome"))
  post <- vcA[vcA$section == "postfilter", ]
  expect_equal(post$total, 1145323)
  expect_equal(post$total_pct, 100)
  expect_equal(post$chrx_snps, 20569)
  # sampleB: targeted vc — region stripped to same tidy col, region col = targetreg
  vcB <- arrow::read_parquet(file.path(odir, grep("sampleB_dragenvar_vc", lf, value = TRUE)))
  expect_true(all(vcB$region == "targetreg"))
  expect_true(all(c("chrx_snps", "qc_region_callability_region1_pct") %in% names(vcB)))
  expect_equal(vcB[vcB$section == "prefilter", ]$chrx_snps, 300)
  # sv: count-only total + pct-paired PASS breakdown
  sv <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_sv", lf, value = TRUE)))
  expect_equal(sv$total_pass, 169)
  expect_equal(sv$del, 50)
  expect_equal(sv$del_pct, 29.59)
  # cnv
  cnv <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_cnv", lf, value = TRUE)))
  expect_equal(cnv$purity_tumor, 0.54)
  expect_equal(cnv$n_amp_pass_pct, 86.54)
  # SEX GENOTYPER preamble captured (not dropped) as two columns on the one cnv row
  expect_equal(nrow(cnv), 1L)
  expect_equal(cnv$sex_karyotype, "XY")
  expect_equal(cnv$sex_genotyper_confidence, 0.95)
  expect_equal(cnv$beta_binomial_overdispersion_m, 200)
  # tmb (4-col, no pct)
  tmb <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_tmb", lf, value = TRUE)))
  expect_equal(tmb$tmb, 3.46)
  expect_equal(tmb$vars_tot_input, 12004)
  # ploidy: split into `ploidystats` (sample scalars) + `ploidyratio` (per-chrom, long)
  plo <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_ploidystats", lf, value = TRUE)))
  expect_equal(plo$ploidy_est, "XX")
  expect_equal(plo$cov_x, 45.99)
  expect_false("cov_x_div_auto" %in% names(plo))
  pcr <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_ploidyratio", lf, value = TRUE)))
  expect_equal(names(pcr)[names(pcr) != "input_id"], c("chrom", "autosomal_ratio"))
  expect_equal(pcr$autosomal_ratio[pcr$chrom == "X"], 0.99)
  expect_equal(pcr$autosomal_ratio[pcr$chrom == "1"], 1.00)
  # sampleB: 'median coverage'/'median / Autosomal median' naming -> same tidy names
  ploB <- arrow::read_parquet(file.path(odir, grep("sampleB_dragenvar_ploidystats", lf, value = TRUE)))
  expect_equal(ploB$cov_x, 19.24)
  expect_equal(ploB$ploidy_est, "XX")
  expect_false("cov_skewness" %in% names(ploB))
  pcrB <- arrow::read_parquet(file.path(odir, grep("sampleB_dragenvar_ploidyratio", lf, value = TRUE)))
  expect_equal(pcrB$autosomal_ratio[pcrB$chrom == "X"], 0.99)
  # nuctrans: long, one row per from->to transition
  nt <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_nuctrans", lf, value = TRUE)))
  expect_equal(names(nt)[names(nt) != "input_id"], c("from", "to", "count"))
  expect_equal(nrow(nt), 12L)
  expect_equal(nt$count[nt$from == "A" & nt$to == "C"], 63)
  expect_equal(nt$count[nt$from == "T" & nt$to == "G"], 45)
  # hethom: per-chromosome, one row per section/rg/chrom; nan ratio preserved
  hh <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_hethom", lf, value = TRUE)))
  expect_true(all(c("section", "rg", "chrom", "het", "hom", "het_hom_ratio") %in% names(hh)))
  pre1 <- hh[hh$section == "prefilter" & hh$chrom == "1", ]
  expect_equal(pre1$het, 233196)
  expect_equal(pre1$het_hom_ratio, 1.348)
  postY <- hh[hh$section == "postfilter" & hh$chrom == "Y", ]
  expect_true(is.nan(postY$het_hom_ratio))
  # hrd (csv, 1 row)
  hrd <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenvar_hrd", lf, value = TRUE)))
  expect_equal(hrd$hrd_score, 5L)
  expect_equal(hrd$loh_score, 2L)
})

