# Generated by roxytest: do not edit by hand!

# File R/DragenFqc.R: @testexamples

test_that("Function DragenFqc() @ L59", {
  
  cls <- DragenFqc; tool <- "dragenfqc"
  indir <- system.file("extdata", tool, package = "tidydragen")
  odir <- tempdir()
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = "run1")
  (lf <- list.files(odir, pattern = "dragenfqc_.*parquet", full.names = FALSE))
  # one file -> 8 flat per-section sub-tables (parser token dropped)
  fqc <- grep("sampleA_dragenfqc_", lf, value = TRUE)
  expect_length(fqc, 8)
  expect_true(all(c(
    "sampleA_dragenfqc_posbasecontent", "sampleA_dragenfqc_posbasemeanqual",
    "sampleA_dragenfqc_posqual", "sampleA_dragenfqc_readgc",
    "sampleA_dragenfqc_readgcqual", "sampleA_dragenfqc_readlen",
    "sampleA_dragenfqc_readmeanqual", "sampleA_dragenfqc_seqpos"
  ) %in% sub("\\.parquet$", "", fqc)))
  pbc <- nemo::read_parquet_grep(odir, fqc, "posbasecontent")
  # per-position base proportion
  expect_equal(round(pbc$prop[pbc$mate == "Read1" & pbc$pos == 1 & pbc$base == "A"], 3), 0.328)
  # binned positions expand to a contiguous 1..50 per-position sequence; pos kept integer
  expect_equal(range(pbc$pos[pbc$mate == "Read1"]), c(1L, 50L))
  expect_equal(length(unique(pbc$pos[pbc$mate == "Read1"])), 50L)
  expect_true(is.integer(pbc$pos))
  # read lengths: 50bp bin
  rl <- nemo::read_parquet_grep(odir, fqc, "readlen")
  expect_true(is.integer(rl$bp))
  expect_equal(rl$reads[rl$mate == "Read1" & rl$bp == 50], 1787127323)
  # positional quality quantile
  pq <- nemo::read_parquet_grep(odir, fqc, "posqual")
  expect_equal(pq$qv[pq$mate == "Read1" & pq$pos == 1 & pq$pct == 25], 37)
  # seqpos: "Total Sequence Starts" summary rows dropped; binned ranges expand per-position
  sp <- nemo::read_parquet_grep(odir, fqc, "seqpos")
  expect_false(any(sp$starts == 254687))
  expect_true(is.integer(sp$bp))
  s1 <- sort(unique(sp$seq))[1]
  spr1 <- sp[sp$mate == "Read1" & sp$seq == s1, ]
  expect_equal(spr1$starts[spr1$bp == 1], 143)
  expect_equal(range(spr1$bp), c(1L, 50L))
  # empty seqpos (adapter never found at a position, only a Total row) still
  # yields an integer bp column; also exercises the path-input branch of tidy_posbasecontent
  d2 <- file.path(tempdir(), "fqempty"); dir.create(d2, showWarnings = FALSE)
  writeLines(c(
    "READ MEAN QUALITY,Read1,Q30 Reads,10",
    "SEQUENCE POSITIONS,Read1,'AGATCGGAAGAG' Total Sequence Starts,5,0.01"
  ), file.path(d2, "sampleZ.fastqc_metrics.csv"))
  ez <- DragenFqc$new(d2)$tidy_posbasecontent(list.files(d2, full.names = TRUE))
  ezsp <- ez$data[[which(ez$name == "seqpos")]]
  expect_equal(nrow(ezsp), 0L)
  expect_true(is.integer(ezsp$bp))
})

