# Generated by roxytest: do not edit by hand!

# File R/DragenMap.R: @testexamples

test_that("Function DragenMap() @ L37", {
  
  cls <- DragenMap; tool <- "dragenmap"
  indir <- system.file("extdata", tool, package = "tidydragen")
  odir <- tempdir()
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = "run1")
  (lf <- list.files(odir, pattern = "dragenmap_.*parquet", full.names = FALSE))
  mapf <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenmap_metrics", lf, value = TRUE)))
  expect_true(all(c("section", "rg", "reads_tot_input", "reads_tot_input_pct", "reads_mapped_pct") %in% names(mapf)))
  # section stripped to phenotype; blank SUMMARY rg -> Total
  expect_true(all(mapf$section %in% c("TUMOR", "NORMAL", "SINGLE")))
  summ <- mapf[mapf$section == "TUMOR" & mapf$rg == "Total", ]
  expect_equal(summ$reads_tot_input, 2635326658)
  expect_equal(summ$reads_mapped_pct, 97.64)
  # run-time metrics: seconds land as the value (not the HH:MM:SS string)
  tf <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenmap_time", lf, value = TRUE)))
  expect_equal(names(tf)[names(tf) != "input_id"][1], "total_runtime")
  expect_equal(tf$total_runtime, 8189.85)
  expect_equal(tf$time_aligning_reads, 2240.12)
  expect_equal(tf$time_sorting, 120)
  expect_equal(tf$time_umi_read_collapsing_and_remapping, 90)
  expect_equal(tf$time_estimating_beta_binomial_overdispersion_wgs, 5)
  # fraglenhist: per-#Sample: blocks split, sample id kept, headers dropped
  fl <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenmap_fraglenhist", lf, value = TRUE)))
  expect_equal(names(fl)[names(fl) != "input_id"], c("sample", "fraglen", "count"))
  expect_setequal(unique(fl$sample), c("sampleA", "sampleA_tn"))
  expect_equal(fl$count[fl$fraglen == 150 & fl$sample == "sampleA"], 12345)
  expect_equal(fl$count[fl$fraglen == 150 & fl$sample == "sampleA_tn"], 999)
})

