# Generated by roxytest: do not edit by hand!

# File R/DragenRna.R: @testexamples

test_that("Function DragenRna() @ L23", {
  
  cls <- DragenRna; tool <- "dragenrna"
  indir <- system.file("extdata", tool, package = "tidydragen")
  odir <- tempdir()
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = "run1", output_id = "out1")
  (lf <- list.files(odir, pattern = "dragenrna_.*parquet", full.names = FALSE))
  fus <- nemo::read_parquet_grep(odir, lf, "sampleA_dragenrna_fusion")
  expect_equal(fus$fusions_all_unfiltered, 7008)
  expect_equal(fus$fusions_unique_passing, 20)
  qnt <- nemo::read_parquet_grep(odir, lf, "sampleA_dragenrna_quant")
  expect_equal(qnt$library_orientation, "ISR")
  expect_equal(qnt$genes_tot, 62700)
  expect_equal(qnt$genes_cov_gt1x_pct, 36.94)
})

