# Generated by roxytest: do not edit by hand!

# File R/DragenBcl.R: @testexamples

test_that("Function DragenBcl() @ L25", {
  
  cls <- DragenBcl; tool <- "dragenbcl"
  indir <- system.file("extdata", tool, package = "tidydragen")
  odir <- tempdir()
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = "run1", output_id = "out1")
  (lf <- list.files(odir, pattern = "dragenbcl_.*parquet", full.names = FALSE))
  dm <- arrow::read_parquet(file.path(odir, "dragenbcl_demultiplexstats.parquet"))
  fq <- arrow::read_parquet(file.path(odir, "dragenbcl_fastqlist.parquet"))
  ri <- arrow::read_parquet(file.path(odir, "dragenbcl_runinfo.parquet"))
  expect_setequal(unique(dm$lane), 1:4)
  expect_setequal(unique(fq$read), 1:2)
  expect_setequal(unique(fq$lane), 1:4)
  expect_equal(nrow(ri), 1L)
  expect_equal(ri$read1_cycles, 151L)
  expect_equal(ri$input_id, "run1")
})

