# Generated by roxytest: do not edit by hand!

# File R/DragenFqc.R: @testexamples

test_that("Function DragenFqc() @ L60", {
  
  cls <- DragenFqc; tool <- "dragenfqc"
  indir <- system.file("extdata", tool, package = "tidydragen")
  odir <- tempdir()
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = "run1")
  (lf <- list.files(odir, pattern = "dragenfqc_.*parquet", full.names = FALSE))
  # one file -> 8 flat per-section sub-tables (parser token dropped)
  fqc <- grep("sampleA_dragenfqc_", lf, value = TRUE)
  expect_length(fqc, 8)
  expect_true(all(c(
    "sampleA_dragenfqc_posbasecontent", "sampleA_dragenfqc_posbasemeanqual",
    "sampleA_dragenfqc_posqual", "sampleA_dragenfqc_readgc",
    "sampleA_dragenfqc_readgcqual", "sampleA_dragenfqc_readlen",
    "sampleA_dragenfqc_readmeanqual", "sampleA_dragenfqc_seqpos"
  ) %in% sub("\\.parquet$", "", fqc)))
  pbc <- arrow::read_parquet(file.path(odir, grep("posbasecontent", fqc, value = TRUE)))
  expect_equal(names(pbc)[names(pbc) != "input_id"], c("mate", "pos", "base", "prop"))
  # base proportion at Read1 pos1: A = 60/(60+20+15+5) = 0.6
  expect_equal(pbc$prop[pbc$mate == "Read1" & pbc$pos == 1 & pbc$base == "A"], 0.6)
  # binned "2-3" position expands to pos 2 and 3; open "256+" -> single pos 256
  expect_setequal(pbc$pos[pbc$mate == "Read1"], c(1, 2, 3, 256))
  expect_true(is.integer(pbc$pos))
  # binned read-length count divided evenly across the span: 40 over 149-150 -> 20 each
  rl <- arrow::read_parquet(file.path(odir, grep("readlen", fqc, value = TRUE)))
  expect_equal(rl$reads[rl$mate == "Read1" & rl$bp == 150], 20)
  expect_equal(rl$reads[rl$mate == "Read1" & rl$bp == 100], 80)
  # open ">=255bp" bin -> single length 255, count kept (not divided)
  expect_equal(rl$reads[rl$mate == "Read1" & rl$bp == 255], 4)
  # positional quality quantile
  pq <- arrow::read_parquet(file.path(odir, grep("posqual", fqc, value = TRUE)))
  expect_equal(pq$qv[pq$mate == "Read1" & pq$pos == 1 & pq$pct == 25], 30)
  # seqpos: "Total Sequence Starts" summary rows dropped; per-position kept
  sp <- arrow::read_parquet(file.path(odir, grep("seqpos", fqc, value = TRUE)))
  expect_equal(sp$starts[sp$mate == "Read1" & sp$bp == 1], 26)
  expect_false(any(sp$starts == 254687))
  # binned "137-140" count split evenly across the 4 positions: 40 -> 10 each
  expect_equal(sp$starts[sp$mate == "Read1" & sp$bp == 138], 10)
  expect_setequal(sp$bp[sp$mate == "Read1"], c(1, 137, 138, 139, 140))
  # empty seqpos (adapter never found at a position, only a Total row) still
  # yields an integer bp column; also exercises the path-input branch of tidy_posbasecontent
  d2 <- file.path(tempdir(), "fqempty"); dir.create(d2, showWarnings = FALSE)
  writeLines(c(
    "READ MEAN QUALITY,Read1,Q30 Reads,10",
    "SEQUENCE POSITIONS,Read1,'AGATCGGAAGAG' Total Sequence Starts,5,0.01"
  ), file.path(d2, "sampleZ.fastqc_metrics.csv"))
  ez <- DragenFqc$new(d2)$tidy_posbasecontent(list.files(d2, full.names = TRUE))
  ezsp <- ez$data[[which(ez$name == "seqpos")]]
  expect_equal(nrow(ezsp), 0L)
  expect_true(is.integer(ezsp$bp))
})

