# Generated by roxytest: do not edit by hand!

# File R/DragenTool.R: @testexamples

test_that("Function DragenTool() @ L37", {
  
  # Abstract base — normally you use a subclass (e.g. DragenVar). The parser/tidier
  # are private; here we just inspect the inherited surface + policy fields.
  indir <- system.file("extdata/dragenmap", package = "tidydragen")
  tool <- DragenTool$new(name = "dragenmap", pkg = "tidydragen", path = indir)
  tool$list_files()      # inherited nemo::Tool file discovery
  tool$on_unmapped       # "error": unmapped metrics abort rather than drop
  tool$on_coerce_fail    # "error": values that fail type coercion abort
  
  # flip a policy to be lenient (drop/keep-NA with a warning instead)
  tool$on_unmapped <- "warn"
  expect_true(inherits(tool, "Tool"))
  expect_gt(nrow(tool$list_files()), 0)
  expect_equal(tool$on_coerce_fail, "error")
  expect_equal(tool$on_unexpected_col, "error")
  expect_equal(tool$on_unmapped, "warn")
})

