# Generated by roxytest: do not edit by hand!

# File R/DragenRna.R: @testexamples

test_that("Function DragenRna() @ L23", {
  
  cls <- DragenRna; tool <- "dragenrna"
  indir <- system.file("extdata", tool, package = "tidydragen")
  odir <- tempdir()
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = "run1", output_id = "out1")
  (lf <- list.files(odir, pattern = "dragenrna_.*parquet", full.names = FALSE))
  fus <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenrna_fusion", lf, value = TRUE)))
  expect_equal(fus$fusions_all_unfiltered, 3078)
  expect_equal(fus$fusions_unique_passing, 2)
  qnt <- arrow::read_parquet(file.path(odir, grep("sampleA_dragenrna_quant", lf, value = TRUE)))
  expect_equal(qnt$library_orientation, "ISR")
  expect_equal(qnt$genes_tot, 62700)
  expect_equal(qnt$genes_cov_gt1x_pct, 33.34)
})

