# Generated by roxytest: do not edit by hand!

# File R/Interop.R: @testexamples

test_that("Function Interop() @ L74", {
  
  cls <- Interop; tool <- "interop"
  # summaries/ kept separate from imaging_tables/ so scanning for one never
  # also matches the other (list_files_dir() recurses; `imaging_table.csv`
  # and `.csv.gz` both match the imagingtable pattern, so a single run over
  # imaging_tables/ picks up BOTH compressed/ and uncompressed/ at once and
  # nemo's generic same-table collision handling disambiguates them, `_2`
  # suffix --- exercised deliberately below, not avoided).
  odir <- tempdir()
  obj_sum <- cls$new(system.file("extdata", tool, "summaries", package = "tidydragen"))
  obj_sum$run(output_dir = odir, format = "parquet", input_id = "run1")
  obj_it <- cls$new(system.file("extdata", tool, "imaging_tables", package = "tidydragen"))
  obj_it$run(output_dir = odir, format = "parquet", input_id = "run1")
  (lf <- list.files(odir, pattern = "interop_.*parquet", full.names = FALSE))
  # summarymain: overall level table (Read1/Read2(I)/Read3(I)/Read4/Non-indexed/Total)
  sm <- arrow::read_parquet(file.path(odir, grep("runA_interop_summarymain\\.parquet$", lf, value = TRUE)))
  expect_setequal(sm$level, c("Read 1", "Read 2 (I)", "Read 3 (I)", "Read 4", "Non-indexed", "Total"))
  expect_equal(sm$yield[sm$level == "Total"], 4196.52)
  # index reads have no PhiX alignment -> error_rate NA (raw "nan")
  expect_true(is.na(sm$error_rate[sm$level == "Read 2 (I)"]))
  # summaryreadlane: per-read x lane x surface detail, "mean +/- sd" / "a / b" cells split
  rl <- arrow::read_parquet(file.path(odir, grep("runA_interop_summaryreadlane\\.parquet$", lf, value = TRUE)))
  expect_equal(nrow(rl), 48L)
  r1l1 <- rl[rl$read == "Read 1" & rl$lane == 1 & is.na(rl$surface), ]
  expect_equal(r1l1$density, 2961)
  expect_equal(r1l1$density_sd, 0)
  expect_equal(r1l1$legacy_phasing_rate, 0.089)
  expect_equal(r1l1$legacy_prephasing_rate, 0.040)
  # non-PhiX-spiked read -> phasing/prephasing rate NA (raw "nan / nan")
  r2l1 <- rl[rl$read == "Read 2 (I)" & rl$lane == 1 & is.na(rl$surface), ]
  expect_true(is.na(r2l1$legacy_phasing_rate))
  # indexsummarymain: per-lane totals
  ix <- arrow::read_parquet(file.path(odir, grep("runA_interop_indexsummarymain\\.parquet$", lf, value = TRUE)))
  expect_equal(nrow(ix), 4L)
  expect_equal(ix$pct_identified[ix$lane == 1], 97.0617)
  # indexsummarydetail: per-index rows
  ixd <- arrow::read_parquet(file.path(odir, grep("runA_interop_indexsummarydetail\\.parquet$", lf, value = TRUE)))
  expect_equal(ixd$sample_id[ixd$lane == 1 & ixd$index_number == 1], "s2600353")
  expect_equal(ixd$index2[ixd$lane == 1 & ixd$index_number == 1], "CTAATAACCG")
  # imagingtable: run-scoped (no run id in filename) -> plain interop_imagingtable
  # name, but compressed/ + uncompressed/ collide on it here -> nemo's `_2`
  # disambiguation kicks in (2 files, identical content, one gz one plain)
  it_files <- grep("^interop_imagingtable(_[0-9]+)?\\.parquet$", lf, value = TRUE)
  expect_length(it_files, 2L)
  it <- do.call(rbind, lapply(it_files, \(f) arrow::read_parquet(file.path(odir, f))))
  expect_equal(nrow(it), 8L) # 4 rows x 2 (compressed + uncompressed)
  r1 <- it[it$tile == 1101 & it$cycle == 1, ]
  expect_equal(unique(r1$density), 2961.300049)
  expect_true(all(is.na(r1$corrected_a))) # raw "nan" -> NA, not NaN
  # PhiX-spiked tile has a real aligned_pct/error_rate; others are NA
  r2 <- it[it$tile == 1103, ]
  expect_true(all(r2$aligned_pct == 0.400000006))
  expect_true(all(is.na(r1$aligned_pct)))
})

