# Generated by roxytest: do not edit by hand!

# File R/utils.R: @testexamples

test_that("Function dragen_cov_metric_normalize() @ L43", {
  
  dragen_cov_metric_normalize(c(
    "Aligned bases",
    "Aligned bases in genome",
    "Average alignment coverage over QC coverage region"
  ))
  
  out <- dragen_cov_metric_normalize(c(
    "Aligned bases",
    "Aligned bases in genome",
    "Average alignment coverage over QC coverage region"
  ))
  expect_equal(out, c(
    "Aligned bases",
    "Aligned bases in region",
    "Average alignment coverage"
  ))
})


test_that("Function dragen_cov_bin_split() @ L78", {
  
  dragen_cov_bin_split(c(
    "PCT of genome with coverage [ 100x: inf)",
    "PCT of QC coverage region with coverage [  20x:  50x)"
  ))
  
  out <- dragen_cov_bin_split(c(
    "PCT of genome with coverage [ 100x: inf)",
    "PCT of QC coverage region with coverage [  20x:  50x)"
  ))
  expect_equal(out$cov_lo, c(100L, 20L))
  expect_equal(out$cov_hi, c(NA_integer_, 50L))
})


test_that("Function fastqc_bin_open() @ L114", {
  
  fastqc_bin_open(c("150", "145-152", "256+", ">=255"))
  
  expect_equal(fastqc_bin_open(c("150", "145-152", "256+", ">=255")),
    c("150", "145-152", "256", "255"))
})


test_that("Function fastqc_bin_expand() @ L145", {
  
  fastqc_bin_expand(c("150", "2-3", "137-140"))
  
  out <- fastqc_bin_expand(c("150", "2-3", "137-140"))
  expect_equal(out[[1]], 150L)
  expect_equal(out[[2]], 2:3)
  expect_equal(out[[3]], 137:140)
})

