# Generated by roxytest: do not edit by hand!

# File R/DragenTso.R: @testexamples

test_that("Function DragenTso() @ L54", {
  
  cls <- DragenTso; tool <- "dragentso"
  indir <- system.file("extdata", tool, package = "tidydragen")
  odir <- tempdir()
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = "run1")
  (lf <- list.files(odir, pattern = "dragentso_.*parquet", full.names = FALSE))
  # smallvariants: CVO [Small Variants] section only; empty-gene row kept
  sv <- arrow::read_parquet(file.path(odir, grep("sampleA_dragentso_smallvariants", lf, value = TRUE)))
  expect_equal(names(sv)[names(sv) != "input_id"],
    c("gene", "chrom", "pos", "ref", "alt", "vaf", "dp", "pdot", "cdot", "csq", "exons"))
  expect_equal(nrow(sv), 3L)
  expect_equal(sv$gene[sv$pos == 2488153], "TNFRSF14")
  expect_true(is.na(sv$gene[sv$pos == 4367323]))
  expect_equal(sv$vaf[sv$pos == 2488153], 0.4768)
  expect_equal(sv$pos[1], 2488153L)
  # fusions: v2 18-column shape, lowercase tidy names
  fu <- arrow::read_parquet(file.path(odir, grep("sampleA_dragentso_fusions", lf, value = TRUE)))
  expect_true(all(c("sample", "name", "chr1", "pos1", "vaf", "is_cosmic_genepair",
    "fusion_directionality_known") %in% names(fu)))
  expect_equal(fu$gene1[1], "BCR")
  expect_equal(fu$vaf[1], 0.28)
  # tmbtrace: 27 v2 columns
  tt <- arrow::read_parquet(file.path(odir, grep("sampleA_dragentso_tmbtrace", lf, value = TRUE)))
  expect_equal(tt$gene[1], "TNFRSF14")
  expect_equal(tt$consequence[1], "missense_variant")
  expect_true("within_valid_tmb_region" %in% names(tt))
  # tmbmsaf: leading max_somatic_af + variant columns
  tm <- arrow::read_parquet(file.path(odir, grep("sampleA_dragentso_tmbmsaf", lf, value = TRUE)))
  expect_equal(names(tm)[2], "max_somatic_af")
  expect_equal(tm$gene[1], "TP53")
  # exoncov / genecov
  ec <- arrow::read_parquet(file.path(odir, grep("sampleA_dragentso_exoncov", lf, value = TRUE)))
  expect_equal(names(ec)[names(ec) != "input_id"],
    c("chrom", "start", "end", "gene", "cov_mean", "cov_median", "cov_min", "cov_max"))
  expect_equal(ec$cov_mean[1], 3004.16)
  gc <- arrow::read_parquet(file.path(odir, grep("sampleA_dragentso_genecov", lf, value = TRUE)))
  expect_false("cov_median" %in% names(gc))
  expect_equal(gc$gene[1], "TNFRSF14")
})

